# Generated by Django 4.0.5 on 2022-06-19 14:19

from django.db import migrations, models
import twittersearch.customfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tweets', twittersearch.customfields.BatchedValuesField()),
            ],
        ),
    ]
