# Generated by Django 4.0.5 on 2022-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoprices', '0004_alter_prices_price'),
        ('twittersearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='crypto',
            field=models.ForeignKey(default='bitcoin', on_delete=django.db.models.deletion.CASCADE, to='cryptoprices.crypto'),
        ),
        migrations.CreateModel(
            name='Tweetcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoprices.crypto')),
            ],
        ),
    ]
