# Generated by Django 4.0.5 on 2022-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoprices', '0004_alter_prices_price'),
        ('twittersearch', '0002_tweets_crypto_tweetcounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoprices.crypto'),
        ),
    ]
