# Generated by Django 4.0.5 on 2022-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=55)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
