# Generated by Django 4.0.5 on 2022-06-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoprices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('nicename', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=5)),
                ('related_keywords', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='prices',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoprices.crypto'),
        ),
    ]
