# Generated by Django 4.0.5 on 2022-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoprices', '0002_crypto_alter_prices_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
