# Generated by Django 4.0.5 on 2022-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoprices', '0003_alter_prices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
