# Generated by Django 4.0.5 on 2022-06-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryptoprices', '0003_alter_prices_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('keywords', models.CharField(max_length=100)),
                ('sentiment', models.DecimalField(decimal_places=6, max_digits=7)),
                ('search_volume', models.IntegerField()),
                ('polarization', models.DecimalField(decimal_places=6, max_digits=7)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoprices.crypto')),
            ],
        ),
    ]
